env:
  browser: true
  es6: true
  jest: true
  jasmine: true
  jquery: true
globals:
  page: true
  path: true
  __dirname: true
  browser: true
  context: true
  module: true
  process: true
  Buffer: true
extends: []
ignorePatterns:
  - '**/tests/*'
  - 'dist/*'
plugins:
  - 'eslint-plugin-prettier'
  - 'eslint-plugin-import'
parser:
  '@typescript-eslint/parser'
parserOptions:
  project: tsconfig-lint.json
  sourceType: module
rules:
  curly:
    - error
    - all
  object-curly-spacing:
    - error
    - always
  array-bracket-spacing:
    - error
    - always
  no-console:
    - error
  indent:
    - error
    - 4
    - { SwitchCase: 1, flatTernaryExpressions: false, ignoreComments: false }
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  constructor-super:
    - error
  for-direction:
    - error
  getter-return:
    - error
  no-async-promise-executor:
    - error
  no-case-declarations:
    - error
  no-class-assign:
    - error
  no-compare-neg-zero:
    - error
  no-cond-assign:
    - error
  no-const-assign:
    - error
  no-constant-condition:
    - error
  no-control-regex:
    - error
  no-debugger:
    - error
  no-delete-var:
    - error
  no-dupe-args:
    - error
  no-dupe-class-members:
    - error
  no-dupe-keys:
    - error
  no-duplicate-case:
    - error
  no-empty:
    - off
  no-empty-character-class:
    - error
  no-empty-pattern:
    - error
  no-ex-assign:
    - error
  no-extra-boolean-cast:
    - error
  no-extra-semi:
    - error
  no-fallthrough:
    - error
  no-func-assign:
    - error
  no-global-assign:
    - error
  no-inner-declarations:
    - error
  no-invalid-regexp:
    - error
  no-irregular-whitespace:
    - error
  no-misleading-character-class:
    - error
  no-mixed-spaces-and-tabs:
    - error
  no-new-symbol:
    - error
  no-obj-calls:
    - error
  no-octal:
    - error
  no-prototype-builtins:
    - error
  no-redeclare:
    - error
  no-regex-spaces:
    - error
  no-self-assign:
    - error
  no-shadow-restricted-names:
    - error
  no-sparse-arrays:
    - error
  no-this-before-super:
    - error
  no-undef:
    - error
  no-unexpected-multiline:
    - error
  no-unreachable:
    - error
  no-unsafe-finally:
    - error
  no-unsafe-negation:
    - error
  no-unused-labels:
    - error
  no-useless-catch:
    - error
  no-useless-escape:
    - error
  no-with:
    - error
  require-yield:
    - error
  use-isnan:
    - error
  valid-typeof:
    - error
  arrow-body-style:
    - error
  camelcase:
    - off
  dot-notation:
    - off
  eol-last:
    - error
  eqeqeq:
      - error
      - smart
  guard-for-in:
    - error
  id-blacklist:
    - off
  id-match:
    - off
  import/no-deprecated:
    - off
  no-bitwise:
    - error
  no-caller:
    - error
  no-eval:
    - error
  no-new-wrappers:
    - error
  no-shadow:
    - error
    - { hoist: "all" }
  no-throw-literal:
    - error
  no-trailing-spaces:
    - error
  no-undef-init:
    - error
  no-underscore-dangle:
    - off
  no-unused-expressions:
    - error
  no-var:
    - error
  prefer-const:
    - error
  radix:
    - error
  spaced-comment:
    - error
